### ISSUE TITLE
error

### ISSUE THREAD

**Issue by vaibhavc418** [0xNanda/Oralyzer#23]
╭─kali@kali ~/Desktop/Tools/Oralyzer ‹master●› 
╰─$ python3 oralyzer.py -u http://testphp.vulnweb.com/showimage.php\?file\=8                                                                                        1 ↵

	Oralyzer

[!] Infusing payloads
Traceback (most recent call last):
  File "/home/kali/Desktop/Tools/Oralyzer/oralyzer.py", line 260, in <module>
    analyze(url)
  File "/home/kali/Desktop/Tools/Oralyzer/oralyzer.py", line 55, in analyze
    testingBreak = request(multiTestCall[1],params)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/Tools/Oralyzer/oralyzer.py", line 74, in request
    funcBreak = check(page, page.request.url)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/Tools/Oralyzer/oralyzer.py", line 215, in check
    sourcesMatch = list(dict.fromkeys(re.findall("|".join(escapedSourcesSinks), str(soup))))
                                                                                ^^^^^^^^^
  File "/home/kali/.local/lib/python3.11/site-packages/bs4/element.py", line 1075, in __unicode__
    return self.decode()
           ^^^^^^^^^^^^^
  File "/home/kali/.local/lib/python3.11/site-packages/bs4/__init__.py", line 626, in decode
    return prefix + super(BeautifulSoup, self).decode(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/.local/lib/python3.11/site-packages/bs4/element.py", line 1111, in decode
    formatter = self.formatter_for_name(formatter)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/.local/lib/python3.11/site-packages/bs4/element.py", line 167, in formatter_for_name
    if isinstance(formatter, collections.Callable):
                             ^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'collections' has no attribute 'Callable'

**Comment by r0075h3ll** [comment]
Hey, this error is related to a specific package in python. Try referring to [this](https://github.com/Datalux/Osintgram/issues/406).
