### ISSUE TITLE
Error!

### ISSUE THREAD

**Issue by ivasugarg** [0xNanda/Oralyzer#4]
Oralyzer {Open Redirection Analyzer}

[•] Appending payloads just after the URL
[•] Infusing payloads
Traceback (most recent call last):
  File "oralyzer.py", line 153, in <module>
    analyze(url)
  File "oralyzer.py", line 96, in analyze
    page = requests.get(uri, allow_redirects=False, headers=header, timeout=15)
  File "/home/marcmx/.local/lib/python3.8/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/marcmx/.local/lib/python3.8/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/marcmx/.local/lib/python3.8/site-packages/requests/sessions.py", line 524, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/marcmx/.local/lib/python3.8/site-packages/requests/sessions.py", line 631, in send
    adapter = self.get_adapter(url=request.url)
  File "/home/marcmx/.local/lib/python3.8/site-packages/requests/sessions.py", line 722, in get_adapter
    raise InvalidSchema("No connection adapters were found for '%s'" % url)
requests.exceptions.InvalidSchema: No connection adapters were found for 'www.google.com/http://www.google.com'

**Comment by 0xNanda** [comment]
fixed
